CREATE TABLE IF NOT EXISTS ausstattung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bezeichnung VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS raum (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    kapazitaet INT NOT NULL CHECK (kapazitaet > 0)
);

CREATE TABLE IF NOT EXISTS raum_ausstattung (
    raum_id BIGINT,
    ausstattung_id BIGINT,
    PRIMARY KEY (raum_id, ausstattung_id),
    FOREIGN KEY (raum_id) REFERENCES raum(id) ON DELETE CASCADE,
    FOREIGN KEY (ausstattung_id) REFERENCES ausstattung(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS modul_ausstattung (
    modul_id BIGINT,
    ausstattung_id BIGINT,
    PRIMARY KEY (modul_id, ausstattung_id),
    FOREIGN KEY (modul_id) REFERENCES modul(id) ON DELETE CASCADE,
    FOREIGN KEY (ausstattung_id) REFERENCES ausstattung(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS matrikel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    anzahl INT NOT NULL CHECK (anzahl > 0)
);

CREATE TABLE IF NOT EXISTS professor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    verfuegbarkeit VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS modul (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    sws INT NOT NULL CHECK (sws > 0),
    schwierigkeitsgrad INT
);

CREATE TABLE IF NOT EXISTS modul_professor (
    modul_id BIGINT,
    professor_id BIGINT,
    PRIMARY KEY (modul_id, professor_id),
    FOREIGN KEY (modul_id) REFERENCES modul(id) ON DELETE CASCADE,
    FOREIGN KEY (professor_id) REFERENCES professor(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vorlesung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modul_id BIGINT NOT NULL,
    matrikel_id BIGINT NOT NULL,
    FOREIGN KEY (modul_id) REFERENCES modul(id) ON DELETE CASCADE,
    FOREIGN KEY (matrikel_id) REFERENCES matrikel(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stundenplan_eintrag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Jede Vorlesungsanforderung bekommt genau einen (oder mehrere, je nach SWS) Termine zugeteilt
    vorlesung_id BIGINT NOT NULL, 
    raum_id BIGINT NOT NULL,
    art VARCHAR(50) NOT NULL,

    wochentag INT NOT NULL CHECK (wochentag BETWEEN 1 AND 5), -- 1 = Montag, 5 = Freitag
    zeitslot INT NOT NULL CHECK (zeitslot BETWEEN 1 AND 6),   -- Block 1 bis 6

    semester VARCHAR(20) NOT NULL,
    kalenderwoche INT,  -- NULL für jede Woche (Regeltermin), oder konkrete KW
    
    FOREIGN KEY (vorlesung_id) REFERENCES vorlesung(id) ON DELETE CASCADE,
    FOREIGN KEY (raum_id) REFERENCES raum(id) ON DELETE CASCADE
);
